ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQVbKym8kCAqXduTE24j3jdDANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjUwMTI4MDYwMDQwWhcNMzUw
  MTI2MDYwMDQwWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCgUVB2o8btgcbQbOzcgWfJZOtCXnqIMAjR
  jsgYqXtck+N3vyJYSW1MGjbiMhQ/oqFlDqQ3//zvFOLQdDiQL8dAolnEG8ydgWuO
  gKcG+n/3eqdPEQKWxUQnmXbv/Pq5uHqxtVhIFMB7d9JtECOFw5uUIkTRFXyScDn1
  sa2bE8jCtahq7xr8KvN3+WcTwLh3tqDUNk/mzYtkN5dAByR5XosWu/fGc+yfD426
  +kqyJeaBms0CPqLgIbGHhdTLpMXLU4vl7LuuRiPxJgbLQh6ML/HgfOa4mixYrG/B
  T+wVQy7np03Na6be9TqZxmjEddyU5RQgu+u2NVzfPg9TPv6dcWN9AgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTjrbFnb98vT9UDVROdvq0Isqyc
  PDAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAcbxGLFiZ+Ldp9QgeB70k2va2sU/1XG51SPmfHopnt4c5
  oW+DqoaKuydQ7WrW0tkNTDJn3QoJeWxRjM++aAjNCJ1+PYU8ON6kGb0dEbbBHiml
  3lcPW+ROdt/mTLUTJRr8bZMw3iv3unTJKkDl9+MrQYKJ3DnR88Q9vvhUK7eyHkIb
  JJp2Xnj/8wrPwj/EtMUJSbmEw8I6Zmtw8fqxLHgRJ69oInm+7tR6SKUpOF5ho56R
  i57SDD38iQ/YQk2w80EgnREC2x/7IX3emE+EtumXI+B2m7VGtKE5inPMDkRr2Gzo
  H7CpiqhO5l0L9puKB5W2uRE+IR8ADX1I/kwN6jF76A==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDRDCCAiygAwIBAgIRAKO6ODere4ddPIq4O/8+5UEwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI1MDIxMzA1NTc0M1oXDTI2
  MDIxMzA1NTc0M1owKjEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMREwDwYDVQQDDAhz
  aWVtX2FwaTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMU83LG1MrPO
  mggpA2fUVeQw7xwhBOFdMj6apx0vqSXFuGoZWS6TEwZHvgOd7lZFMQEqpRrjbLiH
  XqBJf4KYagDes8sagFqbjwS2EnpeBPAA9dLrzVDZhQuNS6AA0LqpPkDjzrhWAalP
  E7t5RZ5E0B1E82UQif4rcABzOdzOrqSSbNozdBb7ZVztrit8MXuGQKm4STT3ZdWX
  lCzjyyiXJDKc5+dEb8oPzIpCfdxYxlUblD5SIJVuPKZzDx4XVL3USlSqNWfAzk5y
  a/2EMDCjfZZkULWVDbZj2HT+Ed6TsWKWWaJ0OCxXQxR28hYRBnqPN2Ud6EJZ66gS
  5+j1xpjpsfcCAwEAAaN1MHMwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsG
  AQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFOOtsWdv
  3y9P1QNVE52+rQiyrJw8MBMGA1UdEQQMMAqCCHNpZW1fYXBpMA0GCSqGSIb3DQEB
  CwUAA4IBAQBBBO/HirknmNDxnnTXWPrM3to9q/j/zE8KDhs2NuwZlN1vYgef0zJI
  t6llJ8Dys0fo5IZ0+Y+hmM+vR6+TlDSxejrD/X4pMzV0Leq5If2hR4jkBPdCC+t8
  7mzz0AlpgOx2DL5vLhtF1oLhG+7Snbazu7k6T3mMeyY6bkKntwiuGUgACsItLokz
  TknoZE0/y9cLBIrVvFchiUbT9YGvT4p4Q89+CLkUWB1vyCk7o0qYIvsE/l9kpiG8
  JXGjcZTjiHwBh2XJ/Y69pOYc6O3PmL2gGEwpNI5PfxVd4IO+KXgkdZ9J4z4C4zvH
  N4So808IXKOr/4tRN++jqJTTSlHmWoqI
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAxTzcsbUys86aCCkDZ9RV5DDvHCEE4V0yPpqnHS+pJcW4ahlZ
  LpMTBke+A53uVkUxASqlGuNsuIdeoEl/gphqAN6zyxqAWpuPBLYSel4E8AD10uvN
  UNmFC41LoADQuqk+QOPOuFYBqU8Tu3lFnkTQHUTzZRCJ/itwAHM53M6upJJs2jN0
  FvtlXO2uK3wxe4ZAqbhJNPdl1ZeULOPLKJckMpzn50Rvyg/MikJ93FjGVRuUPlIg
  lW48pnMPHhdUvdRKVKo1Z8DOTnJr/YQwMKN9lmRQtZUNtmPYdP4R3pOxYpZZonQ4
  LFdDFHbyFhEGeo83ZR3oQlnrqBLn6PXGmOmx9wIDAQABAoIBAFSyuRb698XtD4o3
  ioXY0fWG6fdLWpwoeD4YDXFkGR/mUzYEop50e/PzdO56sHGNjuiwVmxAg1yOjR0J
  0t7S8ppjCBRM0heWu4jLYw33N+mUj/u+VNHGRvLZ/0K7dubhbKFS8l+IV3hMQ+36
  uuGnLTOUe2zH+GoUXyliUdO3UZnLokJ2VESFC5RqYTk/HpYvIjGgfYrcpOI+jWWi
  iZPcIgqwFuFw7CQXc+/Z5NTUnhhaEsC/hOgclt+DZjHavsRDealIGOzK48HiTp4u
  ozgOPl70r4YwVaVLk567wF1upBNBdEjTCHVuRpd0jzOk/5yOtb7qbWI3NH6YAxOg
  MkvCtrkCgYEA4hT/Tq9aqq2sMcQ1PlpXXGdLJkDteT7xYypgfYxrp2q2JuJ0pQrT
  iM2UyTTvgXQW6QW8bbdcNNsTARnG5rFw97/bW9oxlwaXlmLx+uCuzV22bOL2Yub7
  5NVRQzJ/5QG0TqxxfqBw7BzZ5hEaD2940vkrYCfpkd+0qL7JVQyDhzUCgYEA31a0
  UR1HtgE99bdnet9YkWJk2SH9+UwSq1YlU4mLBx7cnYwPCwWlLqYX/axbBldsr2qF
  gp+ef0ioT2Pvo3ZeMWGykTXV3yzNMb7x/7EcOf5hQerDTxzcIbQJ2n7ujZZBftsO
  HGSRwIiN2+zENr/beN1cF7hydGHkgOYMVX7avfsCgYEA3/Xg/Heln5KwFBTEkeI4
  zKbewSRsm0GJKq1eLMEgHBcQHvESkDRrXQgarj+sS1dPIsO16BJOW2XyK5L3gKyi
  tirvCMzbdzrmi+m0wMw3HeYJw1AKt+sN+aCAActS+u93SMB3JfOWKbBjAxBJ+qR4
  0rZXC8g+D23Gr6tgEsp0uUkCgYAYH750cIw5baLqsrfbvtpLQeyQw6oyTnRJy5FW
  l6nLyBqebe2GDEMOaeR3gzGF2tWjkQcA2Ar/xrJfePT+nB+Kh/oI017Zr3YupGhx
  bQkWfpK00w3rsrtYbKEP19wesRc8A59fk8FmoZlpIwcCvvCO+qIi8cpzJcvP3ImC
  hqRMFwKBgGTD00E1vDOLX95cpd4oIrsDZj6sP9Z7qXHNFkI7vrRzBTKZ/NNIAT3p
  EcI9VFESuXWdyMK5JZAPAAeCu4QkghnTxzQNljIeqXjtKkJ0fdoUr+aQMqVWMtTG
  Hvt88O3oSoh50F7M9ehS9xMgYes5J3GMTnxgkEH/aZuCoD7Enuew
  -----END RSA PRIVATE KEY-----
api_connection_string: localhost:8001
name: siem_api
